controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
app.cv_generator:
    path: /api/v1/generate/{provider}
    controller: App\Controller\GeneratorController::generate
    methods: POST
